---
- name: Install MySQL server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Ensure MySQL service is running
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
